# Generated by Django 4.2.1 on 2023-06-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0002_delete_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dexNumber', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('ability', models.CharField(max_length=30)),
            ],
        ),
    ]
